### ISSUE TITLE
require azure_sdk 0.22 fails in containerservice_profile_module.rb

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azure-sdk-for-ruby#2387]
Hello,

if azure_sdk (latest or version 0.22) is rquired within my test ruby file it fails on executing it due to the following error:
```
$ bundle exec ruby  /tmp/azure-test.rb
Traceback (most recent call last):
        10: from /tmp/azure-test.rb:1:in `<main>'
         9: from /tmp/azure-test.rb:1:in `require'
         8: from myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/azure_sdk.rb:7:in `<top (required)>'
         7: from myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/azure_sdk.rb:7:in `require'
         6: from myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/latest/latest_profile_client.rb:19:in `<top (required)>'
         5: from myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/latest/latest_profile_client.rb:19:in `require'
         4: from myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/latest/modules/containerservice_profile_module.rb:7:in `<top (required)>'
         3: from myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/latest/modules/containerservice_profile_module.rb:8:in `<module:Latest>'
         2: from myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/latest/modules/containerservice_profile_module.rb:9:in `<module:ContainerService>'
         1: from myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/latest/modules/containerservice_profile_module.rb:14:in `<module:Mgmt>'
myrbenv/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.22.0/lib/latest/modules/containerservice_profile_module.rb:27:in `<module:Models>': uninitialized constant Azure::ContainerService::Mgmt::V2018_03_31::Models::ContainerServiceServicePrincipalProfile (NameError)
Did you mean?  Azure::ContainerService::Mgmt::V2018_03_31::Models::ContainerServiceDiagnosticsProfile

```

My ruby-test:
```
require 'azure_sdk'

# Provide credentials
options = {
  tenant_id: ENV['AZURE_TENANT_ID'],
  client_id: ENV['AZURE_CLIENT_ID'],
  client_secret: ENV['AZURE_CLIENT_SECRET'],
  subscription_id: ENV['AZURE_SUBSCRIPTION_ID']
}

# Target profile built for Latest Compute
profile_client = Azure::Compute::Profiles::Latest::Mgmt::Client.new(options)
pp profile_client

```

**Comment by sarangan12** [comment]
@tbugfinder Thanks for reporting this issue. The issue has been fixed with the latest release https://rubygems.org/gems/azure_sdk/versions/0.27.1. 

If the issue still exists, feel free to reopen the issue. Thanks

**Comment by tbugfinder** [comment]
@sarangan12 I've run the same tests using azure_sdk 0.31. It failed with:

```
$ bundle exec ruby azure-sdk.rb
Traceback (most recent call last):
        10: from azure-sdk.rb:1:in `<main>'
         9: from azure-sdk.rb:1:in `require'
         8: from /azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/azure_sdk.rb:9:in `<top (required)>'
         7: from /azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/azure_sdk.rb:9:in `require'
         6: from /azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/v2018_03_01/v2018_03_01_profile_client.rb:11:in `<top (required)>'
         5: from /azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/v2018_03_01/v2018_03_01_profile_client.rb:11:in `require'
         4: from /azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/v2018_03_01/modules/network_profile_module.rb:7:in `<top (required)>'
         3: from /azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/v2018_03_01/modules/network_profile_module.rb:8:in `<module:V2018_03_01>'
         2: from /azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/v2018_03_01/modules/network_profile_module.rb:9:in `<module:Network>'
         1: from /azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/v2018_03_01/modules/network_profile_module.rb:48:in `<module:Mgmt>'
/azure_sdk_test/azure-ruby/vendor/bundle/ruby/2.6.0/gems/azure_sdk-0.28.0/lib/v2018_03_01/modules/network_profile_module.rb:50:in `<module:Models>': uninitialized constant Azure::Network::Mgmt::V2017_03_30::Models::EndpointService (NameError)

```

**Comment by tbugfinder** [comment]
Above error is also reported using 0.27.1.
