### ISSUE TITLE
MsRest::DeserializationError on retrieving billing list

### ISSUE THREAD

**Issue by gerardogonzgonz** [Azure/azure-sdk-for-ruby#2458]
Greetings!

I am using 'azure_mgmt_billing' and I am getting the following error at Billing list deserialization:

`ERROR - {
  "exception_message": "{\n  \"exception_message\": null,\n  \"message\": \"Error occured in deserializing the response_body\",\n  \"stacktrace\": null,\n  \"result\": \"2019-04-20\"\n}",
  "message": "Error occurred in deserializing the response",
  "stacktrace": [
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:107:in `deserialize_primary_type'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:64:in `deserialize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:180:in `block in deserialize_composite_type'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:169:in `each'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:169:in `deserialize_composite_type'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:68:in `deserialize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:202:in `block in deserialize_sequence_type'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:201:in `each'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:201:in `deserialize_sequence_type'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:70:in `deserialize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:180:in `block in deserialize_composite_type'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:169:in `each'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:169:in `deserialize_composite_type'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:68:in `deserialize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/ms_rest-0.7.3/lib/ms_rest/serialization.rb:19:in `deserialize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/azure_mgmt_billing-0.17.1/lib/2017-04-24-preview/generated/azure_mgmt_billing/billing_periods.rb:130:in `block in list_async'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promise.rb:533:in `call'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promise.rb:533:in `block in on_fulfill'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/safe_task_executor.rb:24:in `call'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promise.rb:563:in `block in realize'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'",
    "/opt/lib/app/vendor/ruby/2.2.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'"
  ],
  "result": {
    "response": {
      "body": "{\"value\":[{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201907-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201907-1\",\"properties\":{\"billingPeriodStartDate\":\"2019-04-20\",\"billingPeriodEndDate\":\"2019-05-19\"}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201906-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201906-1\",\"properties\":{\"billingPeriodStartDate\":\"2019-03-20\",\"billingPeriodEndDate\":\"2019-04-19\"}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201905-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201905-1\",\"properties\":{\"billingPeriodStartDate\":\"2019-02-20\",\"billingPeriodEndDate\":\"2019-03-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201905-219590150686783\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201904-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201904-1\",\"properties\":{\"billingPeriodStartDate\":\"2019-01-20\",\"billingPeriodEndDate\":\"2019-02-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201904-119965190702909\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201903-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201903-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-12-20\",\"billingPeriodEndDate\":\"2019-01-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201903-119343190692402\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201902-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201902-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-11-20\",\"billingPeriodEndDate\":\"2018-12-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201902-119883190684846\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201901-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201901-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-10-20\",\"billingPeriodEndDate\":\"2018-11-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201901-418250150659134\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201812-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201812-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-09-20\",\"billingPeriodEndDate\":\"2018-10-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201812-418795190671839\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201811-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201811-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-08-20\",\"billingPeriodEndDate\":\"2018-09-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201811-418032150642690\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201810-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201810-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-07-20\",\"billingPeriodEndDate\":\"2018-08-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201810-318184150638557\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201809-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201809-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-06-20\",\"billingPeriodEndDate\":\"2018-07-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201809-318170150622622\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201808-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201808-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-05-20\",\"billingPeriodEndDate\":\"2018-06-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201808-318080150602896\"]}},{\"id\":\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods/201807-1\",\"type\":\"Microsoft.Billing/billingPeriods\",\"name\":\"201807-1\",\"properties\":{\"billingPeriodStartDate\":\"2018-04-20\",\"billingPeriodEndDate\":\"2018-05-19\",\"invoiceIds\":[\"/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/invoices/201807-218250150586541\"]}}],\"nextLink\":\"https://management.azure.com/subscriptions/bd81406c-6028-4037-9f03-9a3af4ff725d/providers/Microsoft.Billing/billingPeriods?api-version=2017-04-24-preview&$skiptoken=MTM%3D\"}",
      "headers": {
        "cache-control": "no-cache",
        "pragma": "no-cache",
        "transfer-encoding": "chunked",
        "content-type": "application/json; charset=utf-8",
        "expires": "-1",
        "vary": "Accept-Encoding",
        "api-supported-versions": "2017-04-24-preview, 2018-03-01-preview",
        "x-content-type-options": "nosniff",
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "x-ms-ratelimit-remaining-subscription-resource-requests": "99",
        "server": "Microsoft-IIS/10.0",
        "x-aspnet-version": "4.0.30319",
        "x-powered-by": "ASP.NET",
        "x-ms-request-id": "ff21b107-d830-4221-8f37-57c24b3d495e",
        "x-ms-correlation-request-id": "ff21b107-d830-4221-8f37-57c24b3d495e",
        "x-ms-routing-request-id": "FRANCECENTRAL:20190515T095112Z:ff21b107-d830-4221-8f37-57c24b3d495e",
        "date": "Wed, 15 May 2019 09:51:12 GMT",
        "connection": "close"
      },
      "status": 200
    },
    "request": {
      "base_uri": "https://management.azure.com",
      "path_template": "subscriptions/{subscriptionId}/providers/Microsoft.Billing/billingPeriods",
      "method": "get",
      "path_params": {
        "subscriptionId": "bd81406c-6028-4037-9f03-9a3af4ff725d"
      },
      "skip_encoding_path_params": null,
      "query_params": {
        "api-version": "2017-04-24-preview",
        "$filter": null,
        "$skiptoken": null,
        "$top": null
      },
      "skip_encoding_query_params": null,
      "headers": {
        "Content-Type": "application/json; charset=utf-8",
        "Accept": "application/json",
        "accept-language": "en-US",
        "x-ms-client-request-id": "e3b7cf4b-5257-43e0-871a-9901c5996402"
      },
      "body": null,
      "middlewares": [
        [
          "MsRest::RetryPolicyMiddleware",
          {
            "times": 3,
            "retry": 0.02
          }
        ],
        [
          "cookie_jar"
        ]
      ],
      "log": null
    }
  }
}`

Could you please take a look at this?

Maybe I am making a mistake but I cannot see it.

Thank you very much!

Regards!

**Comment by gerardogonzgonz** [comment]
Greetings!

After further investigation, my companions at work realized we had a problem with our "Gemfile.lock" file (dependency problems)

I put here our fix just in case it helps other people in the future and close the issue.

Thank you very much!

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    ast (2.4.0)
    azure_mgmt_billing (0.15.1)
      ms_rest_azure (~> 0.9.0)
    azure_mgmt_commerce (0.15.1)
      ms_rest_azure (~> 0.9.0)
    coderay (1.1.2)
    colored (1.2)
    concurrent-ruby (1.1.5)
    domain_name (0.5.20180417)
      unf (>= 0.0.5, < 1.0.0)
    faraday (0.15.4)
      multipart-post (>= 1.2, < 3)
    faraday-cookie_jar (0.0.6)
      faraday (>= 0.7.4)
      http-cookie (~> 1.0.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    logger (1.2.8.1)
    method_source (0.9.2)
    minitest (5.11.3)
    ms_rest (0.7.4)
      concurrent-ruby (~> 1.0)
      faraday (~> 0.9)
      timeliness (~> 0.3.10)
    ms_rest_azure (0.9.0)
      concurrent-ruby (~> 1.0)
      faraday (~> 0.9)
      faraday-cookie_jar (~> 0.0.6)
      ms_rest (~> 0.7.0)
    multipart-post (2.1.1)
    mysql2 (0.3.18)
    parallel (1.17.0)
    parser (2.6.3.0)
      ast (~> 2.4.0)
    powerpack (0.1.2)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    rainbow (2.2.2)
      rake
    rake (12.3.2)
    rubocop (0.51.0)
      parallel (~> 1.10)
      parser (>= 2.3.3.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.10.0)
    thread_safe (0.3.6)
    timeliness (0.3.10)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.6)
    unicode-display_width (1.6.0)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport (= 5.1.4)
  azure_mgmt_billing (= 0.15.1)
  azure_mgmt_commerce (= 0.15.1)
  colored
  logger (~> 1.2.8)
  ms_rest_azure (~> 0.9.0)
  mysql2 (= 0.3.18)
  pry
  rubocop (~> 0.51.0)
