### ISSUE TITLE
Disk service Azure.vm_disk_management errors out

### ISSUE THREAD

**Issue by gregohardy** [Azure/azure-sdk-for-ruby#269]
```
/Users/greghardy/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/azure-0.7.0/lib/azure/client_services.rb:53:in `vm_disk_management': uninitialized constant Azure::VirtualMachineImageManagement::VirtualMachineDiskManagementService (NameError)
        from /Users/greghardy/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/azure-0.7.0/lib/azure.rb:141:in `method_missing'
        from destroy.rb:17:in `<main>'
```
It appears that client_service.rb file is missing a require?

The work around for me was to add this line to my script
```
require 'azure/virtual_machine_image_management/virtual_machine_image_management_service'
```

**Comment by devigned** [comment]
oh no... Must be a missed autoload. We'll fix that.
