### ISSUE TITLE
concurrent-ruby rooted stack traces make problems hard to find

### ISSUE THREAD

**Issue by fdr** [Azure/azure-sdk-for-ruby#2798]
Even when making synchronous calls, stack traces for API failures will be rooted in the `concurrent-ruby` library, kind of like the one seen below. You wouldn't know it from this output, but this is part of an rspec test I was working on.

In this case the problem is not so bad, but this behavior has been bothering me for a while: it really messes up using exception catching programs (sentry, airbrake, etc) and can confuse development as well.

I have two (largely mutually exclusive) proposals:

* avoid thread pools when calling synchronous methods, call the HTTP client in-fiber (e.g. around `ms_rest/http_operation_request.rb`). This would make the client a lot more like all others.

* Generate code such that it catches and re-wraps exceptions every time a promise is forced by the SDK, and that exception will have stacks in the current fiber. If an integrating program uses the promises directly, this wrapping and handling of stacks is necessarily their problem; nothing to do in the SDK...so the async versions can remain as-is.

```
     Failure/Error:
       fail AzureOperationError,
         'Couldn\'t login to Azure, please verify your tenant id, client id and client secret' unless response.status == 200
     
     MsRestAzure::AzureOperationError:
       {
         "message": "Couldn't login to Azure, please verify your tenant id, client id and client secret",
         "request": null,
         "response": null
       }
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/ms_rest_azure-0.12.0/lib/ms_rest_azure/credentials/application_token_provider.rb:114:in `acquire_token'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/ms_rest_azure-0.12.0/lib/ms_rest_azure/credentials/application_token_provider.rb:75:in `get_authentication_header'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/ms_rest-0.7.6/lib/ms_rest/credentials/token_credentials.rb:49:in `sign_request'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/ms_rest-0.7.6/lib/ms_rest/service_client.rb:51:in `block in make_request_async'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/ms_rest-0.7.6/lib/ms_rest/http_operation_request.rb:83:in `block (3 levels) in run_promise'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:489:in `block in run_request'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:506:in `block in build_request'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/request.rb:55:in `block in create'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/request.rb:54:in `tap'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/request.rb:54:in `create'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:502:in `build_request'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:484:in `run_request'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/ms_rest-0.7.6/lib/ms_rest/http_operation_request.rb:81:in `block (2 levels) in run_promise'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/ms_rest-0.7.6/lib/ms_rest/http_operation_request.rb:80:in `loop'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/ms_rest-0.7.6/lib/ms_rest/http_operation_request.rb:80:in `block in run_promise'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/promise.rb:563:in `block in realize'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
     # /home/fdr/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
```

**Comment by MyronFanQiu** [comment]
@fdr Thanks for raising this issue. We would take a look. To be honest, we don't have too much bandwidth on ruby SDK. It need some time for us to investigate.

**Comment by fdr** [comment]
The SDK works pretty well, so please do not let it slide into disrepair, which is probably the most important thing. Thanks for taking care of it.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
