### ISSUE TITLE
ASM use Azure.management_certificate has exception

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-sdk-for-ruby#388]
Code 
require 'azure'
Azure.management_certificate = "C:\OpenSSL-Win64\bin\lilicert.pem"
Azure.subscription_id        = "id"
vm_management = Azure.vm_management

Exception
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/azure-0.7.5/lib/azure/configurable.rb:184:in `rescue in management_certificate=': Management certificate not valid. Error: PKCS12_parse: mac verify failure (ArgumentError)
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/azure-0.7.5/lib/azure/configurable.rb:167:in `management_certificate='
	from C:/Bitnami/wampstack-5.5.34-0/apache2/htdocs/liliruby/lili.rb:4:in `<main>'

**Comment by LiliDeng** [comment]
resolve by specify Azure.management_certificate = "C:\\OpenSSL-Win64\\bin\\lilicert.pem"
