### ISSUE TITLE
Service Bus topics: Faraday::ConnectionFailed

### ISSUE THREAD

**Issue by Dunkirk** [Azure/azure-sdk-for-ruby#426]
The docs just don't work.

```
require 'azure'
Azure.config.sb_namespace='<namespace>'
Azure.config.sb_access_key='<key>'
servicebus = Azure::ServiceBus::ServiceBusService.new
servicebus.create_topic 'topic1'
servicebus.create_subscription 'topic1', 'subscription1'
```

/Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: nodename nor servname provided, or not known (Faraday::ConnectionFailed)

ruby 2.2.1, faraday 0.9.2, azure 0.7.5, azure-core 0.1.2

**Comment by veronicagg** [comment]
@Dunkirk Have you looked into https://github.com/Azure/azure-sdk-for-ruby/issues/396 ? 
Are you using ACS or SAS? Are you seeing your service bus namespace appear in the azure portal? If you're using ACS ( #396 ), the 'Default Key' to use as access_key is only seen in the Classic Azure portal under Connection Information (when you select the service bus namespace).

**Comment by Dunkirk** [comment]
SAS, and, yes, I see the queue(s) in the portal.

```
david@farragut:~/Projects/ejr_tracker/lib$ irb

2.2.1 :001 > require 'azure'
 => true 

2.2.1 :003 > Azure.config.sb_namespace='xxx'
 => "xxx" 

2.2.1 :004 > Azure.config.sb_access_key='yyyy'
 => "yyyy" 

2.2.1 :005 > sbs = Azure::ServiceBus::ServiceBusService.new
 => #<Azure::ServiceBus::ServiceBusService:0x007fe1b48c5468 @host="https://xxx.servicebus.windows.net", @client=Azure, @filters=[#<Azure::Core::Http::SignerFilter:0x007fe1b48c52d8 @signer=#<Azure::ServiceBus::Auth::WrapSigner:0x007fe1b48c53c8 @tokens={}, @wrap_service=#<Azure::ServiceBus::Auth::WrapService:0x007fe1b48c5378 @host="https://tasacdws-sb.accesscontrol.windows.net", @client=Azure, @filters=[], @issuer="owner", @access_key="yyyy">>>, #<Proc:0x007fe1b48c5260@/Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.5/lib/azure/service_bus/service_bus_service.rb:35>], @account_name=nil, @signer=#<Azure::ServiceBus::Auth::WrapSigner:0x007fe1b48c53c8 @tokens={}, @wrap_service=#<Azure::ServiceBus::Auth::WrapService:0x007fe1b48c5378 @host="https://tasacdws-sb.accesscontrol.windows.net", @client=Azure, @filters=[], @issuer="owner", @access_key="yyyy">>> 

2.2.1 :007 > q = sbs.get_queue("report")
Faraday::ConnectionFailed: getaddrinfo: nodename nor servname provided, or not known
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
... 4 levels...
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.5/lib/azure/service_bus/auth/wrap_signer.rb:53:in `get_access_token'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.5/lib/azure/service_bus/auth/wrap_signer.rb:46:in `sign'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.5/lib/azure/service_bus/auth/wrap_signer.rb:41:in `sign_request'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.2/lib/azure/core/http/signer_filter.rb:27:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.2/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.5/lib/azure/service_bus/service_bus_service.rb:41:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.5/lib/azure/service_bus/service_bus_service.rb:41:in `block in initialize'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.2/lib/azure/core/http/http_request.rb:104:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.2/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.2/lib/azure/core/service.rb:36:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.2/lib/azure/core/filtered_service.rb:34:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.2/lib/azure/core/signed_service.rb:41:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.5/lib/azure/service_bus/service_bus_service.rb:775:in `resource_entry'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.5/lib/azure/service_bus/service_bus_service.rb:144:in `get_queue'
	from (rib):7
	from /Users/david/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'2.2.1 :008 > 
```

Am I missing something really, really basic? I've tried to trace this call all the way through the Faraday library, but I don't really know what I'm looking for. Every code example I can find on using this library gives me that same error when it comes to actually doing something useful with a ServiceBus object. The Faraday lib seems to be stuck on looking for the name of the service, like xxx.servicebus.windows.net, but my "sbs" object, above, shows that the definition looks good. It's like azure or azure-core aren't passing something correctly?

**Comment by Dunkirk** [comment]
I'm just noticing that there are 2 references to xxx-sb.accesscontrol.windows.net. The azure lib is generating this as part of the ServiceBusService object, but that name doesn't resolve.

**Comment by veronicagg** [comment]
@Dunkirk I've made a fix regarding SAS for Service Bus and added a test as an example for creating a Service Bus using SAS. Please take a look at this commit https://github.com/Azure/azure-sdk-for-ruby/commit/09ab24e511889d41a1fef4755217baa595a279f5 and let me know if it helps. Thanks!

**Comment by Dunkirk** [comment]
@veronicagg No change. I note that it seems that I should be using `Azure.config.sb_sas_key` instead of `Azure.config.sb_access_key`, but that didn't make a difference either.

I tried setting up the service bus object by specifying the host, as you have in queues_test.rb, but got an error:

```
2.2.1 :003 > signer = Azure::ServiceBus::Auth::SharedAccessSigner.new
NameError: uninitialized constant Azure::ServiceBus::Auth
	from (rib):3
	from /Users/david/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

I know I've got the right commit; the repo looks very different at that commit:

```
david@farragut:~/Projects/ejr_tracker/lib$ bundle show azure
/Users/david/.rvm/gems/ruby-2.2.1/bundler/gems/azure-sdk-for-ruby-09ab24e51188
```

I'm still totally lost.

**Comment by veronicagg** [comment]
@Dunkirk Regarding the key, yes, sb_sas_key is the one to use if you're using SAS for your Service Bus. 
The line `signer = Azure::ServiceBus::Auth::SharedAccessSigner.new` is used to create a SharedAccessSigner object that you can pass as signer when creating the ServiceBusService. 
The error "uninitialized constant Azure::ServiceBus::Auth" indicates the class is not defined in your environment, was require 'azure' ran? (if you'd like to run with the latest source code, you'd need to point the gem path to a location that contains it as well)

**Comment by Dunkirk** [comment]
Yes, I'm quite certain I'm requiring it in irb, and it's being included via Bundler in the rails console. I can use a double-tab to give me suggestions for Azure::<> and Azure::ServiceBus::<> namespaces, but Auth is not in them.

**Comment by Dunkirk** [comment]
I tried running the test:

```
david@farragut:~/Projects/azure-sdk-for-ruby$ ruby -I"lib:test" test/integration/service_bus/queues_test.rb
/Users/david/Projects/azure-sdk-for-ruby/lib/azure/configurable.rb:184:in `rescue in management_certificate=': Management certificate not valid. Error: PKCS12_parse: mac verify failure (ArgumentError)
```

I created a certificate as per the docs (https://azure.microsoft.com/en-us/documentation/articles/cloud-services-certs-create/), and I successfully uploaded it via the old portal. I've tried referencing both the .pfx and the .cer files in .env, but both give me the error above.

**Comment by Dunkirk** [comment]
I created the PFX file according to https://github.com/Azure/azure-sdk-for-ruby/tree/asm#storage, and the now test works just fine.

```
david@farragut:~/Projects/azure-sdk-for-ruby$ ruby -I"lib:test" test/integration/service_bus/queues_test.rb
Run options: --seed 18573

# Running:

..................

Finished in 0.762713s, 23.6000 runs/s, 124.5553 assertions/s.

18 runs, 95 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by veronicagg** [comment]
@Dunkirk Good to hear you're able to run the tests, the one at https://github.com/Azure/azure-sdk-for-ruby/blob/asm/test/integration/service_bus/queues_test.rb#L218 is running very similar code to what I was referring before. Is the service bus scenario you wanted to run working now? If not, what's the error you're seeing now?

**Comment by mydiemho** [comment]
@veronicagg I am having similar problems when trying to run the code.  I have follow the example in your commit.

https://gist.github.com/mydiemho/90b8da9bbb51d78a7706f5a6fbb68790


################
require 'azure'

lib/message_queue/azure_queue.rb:37:in `<class:AzureQueue>': uninitialized constant Azure::ServiceBus::Auth (NameError)

#################
require 'azure'
require 'azure/service_bus/auth/shared_access_signer'

/Users/mho/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/azure-0.7.5/lib/azure/service_bus/auth/shared_access_signer.rb:6:in `<module:Auth>': uninitialized constant Azure::Core (NameError)
        from /Users/mho/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/azure-0.7.5/lib/azure/service_bus/auth/shared_access_signer.rb:5:in `<module:ServiceBus>'
        from /Users/mho/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/azure-0.7.5/lib/azure/service_bus/auth/shared_access_signer.rb:4:in `<module:Azure>'
        from /Users/mho/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/azure-0.7.5/lib/azure/service_bus/auth/shared_access_signer.rb:3:in `<top (required)>'

**Comment by mydiemho** [comment]
@veronicagg I was able to get to the next step by adding [1] but now I come upon 401 error:

[1]
require 'azure'
require 'azure/service_bus/service_bus_service'

[2]
#<Azure::ServiceBus::ServiceBusService:0x007fa8b5649320>
/Users/mho/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/azure-core-0.1.4/lib/azure/core/http/http_request.rb:147:in `call': Unknown (401):  (Azure::Core::Http::HTTPError)

**Comment by mydiemho** [comment]
I was able to get the code working by pointing my gem to the latest code change:

<GEMFILE>
gem 'azure', path: '<PATH>/azure-sdk-for-ruby'

**Comment by veronicagg** [comment]
@mydiemho Thanks for confirming it's working for you! We'll release an updated version of the gem soon.

**Comment by veronicagg** [comment]
'azure' gem version 0.7.6 is now released https://rubygems.org/gems/azure/versions/0.7.6, feel free to let us know how it works for you, thanks!

**Comment by Dunkirk** [comment]
Using the same values for the config variables that made the tests pass, I have:

```
require 'azure'
Azure.config.sb_access_key='aaaaaaaaaa'
Azure.config.sb_sas_key='bbbbbbbbbb'
Azure.config.management_certificate='/Users/david/Projects/azure-sdk-for-ruby/cccccccc-8-27-2016-credentials.pfx'
Azure.config.subscription_id='ddddddddddd'
Azure.config.sb_namespace='eeeeeeeeee'
sbs = Azure::ServiceBus::ServiceBusService.new
q = sbs.get_queue("report")
m = Azure::ServiceBus::BrokeredMessage.new("test queue message")
m.correlation_id = "test-correlation-id"
sbs.send_queue_message("test-queue", message)
```

```
david@farragut:~/Projects/ejr_tracker/lib$ ruby asdf.rb
/Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: nodename nor servname provided, or not known (Faraday::ConnectionFailed)
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.6/lib/azure/http_response_helper.rb:27:in `set_up_response'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.4/lib/azure/core/http/http_request.rb:143:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.4/lib/azure/core/service.rb:36:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.4/lib/azure/core/filtered_service.rb:34:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.6/lib/azure/service_bus/auth/wrap_service.rb:43:in `get_access_token'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.6/lib/azure/service_bus/auth/wrap_signer.rb:53:in `get_access_token'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.6/lib/azure/service_bus/auth/wrap_signer.rb:46:in `sign'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.6/lib/azure/service_bus/auth/wrap_signer.rb:41:in `sign_request'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.4/lib/azure/core/http/signer_filter.rb:27:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.4/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.4/lib/azure/core/service.rb:36:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.4/lib/azure/core/filtered_service.rb:34:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-core-0.1.4/lib/azure/core/signed_service.rb:41:in `call'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.6/lib/azure/service_bus/service_bus_service.rb:775:in `resource_entry'
	from /Users/david/.rvm/gems/ruby-2.2.1/gems/azure-0.7.6/lib/azure/service_bus/service_bus_service.rb:144:in `get_queue'
	from asdf.rb:8:in `<main>'
```

**Comment by veronicagg** [comment]
@Dunkirk Could you try the following?:

```ruby
require 'azure'
require 'azure/service_bus/service_bus_service'

Azure.configure do |config|
    config.sb_namespace             = <your_sb_namespace>
    config.sb_sas_key_name          = <your_sas_key_name> # you can use "RootManageSharedAccessKey" just for the purpose of this test
    config.sb_sas_key               = <your_sas_key>
end

signer = Azure::ServiceBus::Auth::SharedAccessSigner.new # if you want to use SAS you need to create a signer
sb_host = "https://#{Azure.sb_namespace}.servicebus.windows.net"
sbs = Azure::ServiceBus::ServiceBusService.new(sb_host, { signer: signer}) # if you want to use SAS you need to pass the signer when creating ServiceBusService
sbs.create_queue "test-queue2" # this line creates the queue, so you should run it only the first time, you can comment it out afterwards, if you want to send more messages to this queue
message = Azure::ServiceBus::BrokeredMessage.new("test queue message")
message.correlation_id = "test-correlation-id"
sbs.send_queue_message("test-queue2", message) # please make sure you have the right name of the queue you want to send messages to as the first argument, and the message in the second one
```

**Comment by Dunkirk** [comment]
That worked! I always figured it was a function of setting the right variables, and I hadn't been specifying the key name, only the key itself. Whew! Finally! Thank you!

**Comment by veronicagg** [comment]
@Dunkirk Glad to hear that! Thanks.

**Comment by Dunkirk** [comment]
In case someone finds this later, in getting this to work with Rails, you have to include the 'azure' gem in the Gemfile, but you also need to `require 'azure/service_bus/service_bus_service'` in whatever method you use to create a message.

**Comment by veronicagg** [comment]
@Dunkirk Correct. After the next release of azure-core gem if should not be needed anymore due to this commit https://github.com/Azure/azure-ruby-asm-core/commit/dddb111b485973ad9f422f9c405cc5ce3ebebb2d.

**Comment by pedro-brentan** [comment]
@veronicagg When event hubs will be supported by the gem?
