### ISSUE TITLE
Azure SQL Missing Operations

### ISSUE THREAD

**Issue by waqar-haider-confiz** [Azure/azure-sdk-for-ruby#484]
What are plans for adding support in Azuer SQL for following operations;
- Server Management (Create/Update/Get/List)
- Database Management (Create/Update/Get/List)
- Data ware house Management 

Thanks

**Comment by vishrutshah** [comment]
Hello @waqar-haider-confiz,

We have updated our [azure_mgmt_sql](https://rubygems.org/gems/azure_mgmt_sql/versions/0.8.0) sdk using latest swagger. Could you please let us know whether you are still missing some functionalities?

Database Management + Data ware house Management: https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/databases.rb

Server Management: https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/servers.rb

Thanks!

**Comment by atistler** [comment]
calling servers.list appears to return XML and not JSON and triggers a MsRest::DeserializationError

GET http://management.azure.com:443/subscriptions/*************************/providers/Microsoft.Sql/servers?api-version=2014-04-01

```
=> {"exception_message"=>
  "lexical error: invalid char in json text.\n                                       <?xml version=\"1.0\" encoding=\"u\n                     (right here) ------^\n",
 "message"=>"Error occurred in deserializing the response",
 "stacktrace"=>
  ["/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/yajl-ruby-1.3.0/lib/yajl/json_gem/parsing.rb:23:in `rescue in load'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/yajl-ruby-1.3.0/lib/yajl/json_gem/parsing.rb:20:in `load'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/azure_mgmt_sql-0.8.0/lib/generated/azure_mgmt_sql/servers.rb:521:in `block in list_async'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/promise.rb:497:in `block in on_fulfill'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/promise.rb:527:in `block in realize'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'",
   "/Users/atistler/.rvm/gems/ruby-2.3.1@ccp/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'"],
 "result"=>
  {"response"=>
    {"body"=>
      "<?xml version=\"1.0\" encoding=\"utf-8\"?><feed xml:base=\"https://management.database.windows.net:8443/v2/ManagementService.Trusted.svc/modules/ServerManagement/\" xmlns=\"http://www.w3.org/20
     "headers"=>
      {"cache-control"=>"no-store, no-cache",
       "content-length"=>"4514",
       "content-type"=>"application/atom+xml; type=feed; charset=utf-8",
       "x-ms-request-id"=>"b03c4968-9736-448c-83b2-92d0791f0db6",
       "x-content-type-options"=>"nosniff",
       "dataserviceversion"=>"1.0;",
       "server"=>"Microsoft-HTTPAPI/2.0",
       "x-ms-ratelimit-remaining-subscription-reads"=>"14997",
       "x-ms-correlation-request-id"=>"929c6070-d8c5-44ec-9b84-e6014201a6fa",
       "x-ms-routing-request-id"=>
        "EASTUS2:20161121T032645Z:929c6070-d8c5-44ec-9b84-e6014201a6fa",
       "strict-transport-security"=>"max-age=31536000; includeSubDomains",
       "date"=>"Mon, 21 Nov 2016 03:26:44 GMT",
       "connection"=>"close"},
     "status"=>200},
   "request"=>
    {"base_uri"=>"https://management.azure.com",
     "path_template"=>
      "/subscriptions/{subscriptionId}/providers/Microsoft.Sql/servers",
     "method"=>"get",
     "path_params"=>{"subscriptionId"=>"****************************************"},
     "skip_encoding_path_params"=>nil,
     "query_params"=>{"api-version"=>"2014-04-01"},
     "skip_encoding_query_params"=>nil,
     "headers"=>
      {"Content-Type"=>"application/json;charset=utf-8",
       "accept-language"=>"en-US",
       "x-ms-client-request-id"=>"b028ee0c-1ecc-4f3c-9624-187ac84f3b97"},
     "body"=>nil,
     "middlewares"=>
      [[{"load_error"=>nil}, {"times"=>3, "retry"=>0.02}], ["cookie_jar"]],
     "log"=>nil}}}
```

**Comment by atistler** [comment]
Content type is set correctly: "application/json;charset=utf-8".  Appears to be a server side problem

**Comment by nathannfan** [comment]
Can't repro in fiddler - I'm getting JSON back.  I'm guessing it's got something to do with the request headers - could someone share the request headers that the ruby client is using?

**Comment by atistler** [comment]
I was able to get this working however i had to pass a custom header:

sql_connection.servers.list('Accept' => 'application/json')

**Comment by waqar-haider-confiz** [comment]
Hey @vishrutshah ,

Thanks for updating the SDK with suggested functionalities in this issue.
