### ISSUE TITLE
Azure Recovery Services Backup CloudInternalError

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [Azure/azure-sdk-for-ruby#642]
Hi @vishrutshah 

I am having an issue while using `Azure Recovery Services Backup` component `ProtectionContainers`.
This is the script I am using to `list` the `ProtectionContainers` is
```
require 'azure_mgmt_recovery_services_backup'

subscription_id = '########-####-####-####-############'
provider = MsRestAzure::ApplicationTokenProvider.new('########-####-####-####-############',
                                                     '########-####-####-####-############',
                                                     '############################################'
)
credentials = MsRest::TokenCredentials.new(provider)

recovery_services = Azure::ARM::RecoveryServicesBackup::RecoveryServicesBackupClient.new(credentials)
recovery_services.subscription_id = subscription_id

recovery_services.protection_containers.list('TestVault', 'TestRG-RV')
```

Running this script gives me a `MsRestAzure::AzureOperationError: CloudInternalError`. The complete error log is
```
/var/lib/gems/2.3.0/gems/azure_mgmt_recovery_services_backup-0.8.0/lib/generated/azure_mgmt_recovery_services_backup/protection_containers.rb:221:in `block in list_async': { (MsRestAzure::AzureOperationError)
  "message": "MsRestAzure::AzureOperationError: CloudInternalError: Microsoft Azure Backup encountered an internal error.\r\nWait for a few minutes and then try the operation again. If the issue persists, please contact Microsoft support.",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{vaultName}/backupProtectionContainers",
    "method": "get",
    "path_params": {
      "vaultName": "TestVault",
      "resourceGroupName": "TestRG-RV",
      "subscriptionId": "########-####-####-####-############"
    },
    "skip_encoding_path_params": null,
    "query_params": {
      "api-version": "2016-06-01",
      "$filter": null
    },
    "skip_encoding_query_params": null,
    "headers": {
      "Content-Type": "application/json;charset=utf-8",
      "accept-language": "en-US",
      "x-ms-client-request-id": "3463914c-34bc-45d4-ba77-65852d8d8270"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "{\"error\":{\"code\":\"CloudInternalError\",\"message\":\"Microsoft Azure Backup encountered an internal error.\\r\\nWait for a few minutes and then try the operation again. If the issue persists, please contact Microsoft support.\",\"target\":null,\"details\":null,\"innerError\":null}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-length": "269",
      "content-type": "application/json",
      "x-ms-request-id": "4d55e5fe-331a-4f45-a6f7-3c5819b5c214",
      "x-ms-client-request-id": "3463914c-34bc-45d4-ba77-65852d8d8270, 3463914c-34bc-45d4-ba77-65852d8d8270",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "server": "Microsoft-IIS/8.0",
      "x-powered-by": "ASP.NET",
      "x-ms-failure-cause": "service",
      "x-ms-ratelimit-remaining-subscription-reads": "14966",
      "x-ms-correlation-request-id": "4d55e5fe-331a-4f45-a6f7-3c5819b5c214",
      "x-ms-routing-request-id": "WESTEUROPE:20170109T105903Z:4d55e5fe-331a-4f45-a6f7-3c5819b5c214",
      "date": "Mon, 09 Jan 2017 10:59:03 GMT",
      "connection": "close"
    },
    "status": 500
  }
}
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/promise.rb:501:in `block in on_fulfill'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/promise.rb:531:in `block in realize'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

Process finished with exit code 1
```

Running this script after waiting a few minutes does not solve this issue.

My question is, what does this error represent and how can I resolve it?

Thanks

**Comment by vishrutshah** [comment]
@markgalioto / @dragonfly91 Could you please help us out here on why server might be throwing `Internal Server Error` - 500 error for `list` operation for `ProtectionContainers` from server side? 

Thanks,

**Comment by bilal-naeem-confiz** [comment]
Hi @vishrutshah 

Is there any update on this issue?

**Comment by vishrutshah** [comment]
Moving to milestone `v0.10.0-arm` as we are waiting from service team.

**Comment by johnwc** [comment]
The issue resolves around the list functionality requires a BackupManagementType to be sent in the API request.
In .Net you would call this same method like so to get the filter added to the query string.

```
BackupManagementType containerType = BackupManagementType.AzureIaasVM;
client.ProtectionContainers.List("TestVault", "TestRG-RV", new ODataQuery<BMSContainerQueryObject>(d => d.BackupManagementType == containerType))
```

**Comment by bilal-naeem-confiz** [comment]
I have updated my script using the latest version of the `azure_mgmt_recovery_services_backup` gem
```
require 'azure_mgmt_recovery_services_backup'

subscription_id = '########-####-####-####-############'
provider = MsRestAzure::ApplicationTokenProvider.new('########-####-####-####-############',
                                                     '########-####-####-####-############',
                                                     '############################################'
)
credentials = MsRest::TokenCredentials.new(provider)

recovery_services = Azure::ARM::RecoveryServicesBackup::RecoveryServicesBackupClient.new(credentials)
recovery_services.subscription_id = subscription_id

recovery_services.backup_protection_containers.list('TestVault', 'TestRG-RV')
```

The error that I now get is
```
/var/lib/gems/2.3.0/gems/azure_mgmt_recovery_services_backup-0.11.0/lib/generated/azure_mgmt_recovery_services_backup/backup_protection_containers.rb:104:in `block in list_async': { (MsRestAzure::AzureOperationError)  "message": "MsRestAzure::AzureOperationError: BMSUserErrorInvalidInput: Input provided for the call is invalid\r\nPlease check the required inputs",  "request": {    "base_uri": "https://management.azure.com",    "path_template": "Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{vaultName}/backupProtectionContainers",    "method": "get",    "path_params": {
      "vaultName": "TestVault",      "resourceGroupName": "TestRG-RV",
      "subscriptionId": "8339d243-d139-4e55-addf-e94fd402d8ff"
    },
    "skip_encoding_path_params": null,
    "query_params": {
      "api-version": "2016-12-01",
      "$filter": null
    },
    "skip_encoding_query_params": null,
    "headers": {
      "Content-Type": "application/json;charset=utf-8",
      "Accept": "application/json",
      "accept-language": "en-US",
      "x-ms-client-request-id": "788bbb1f-2b77-416e-9b21-8867a6e5434e"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "{\"error\":{\"code\":\"BMSUserErrorInvalidInput\",\"message\":\"Input provided for the call is invalid\\r\\nPlease check the required inputs\",\"target\":null,\"details\":null,\"innerError\":null}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-length": "179",
      "content-type": "application/json",
      "x-ms-request-id": "b3d225fd-43fa-45f6-a733-c8f6ced035d0",
      "x-ms-client-request-id": "788bbb1f-2b77-416e-9b21-8867a6e5434e, 788bbb1f-2b77-416e-9b21-8867a6e5434e",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "server": "Microsoft-IIS/8.0",
      "x-powered-by": "ASP.NET",
      "x-ms-ratelimit-remaining-subscription-reads": "14936",
      "x-ms-correlation-request-id": "b3d225fd-43fa-45f6-a733-c8f6ced035d0",
      "x-ms-routing-request-id": "CANADAEAST:20170825T113037Z:b3d225fd-43fa-45f6-a733-c8f6ced035d0",
      "date": "Fri, 25 Aug 2017 11:30:36 GMT",
      "connection": "close"
    },
    "status": 400
  }
}
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/promise.rb:501:in `block in on_fulfill'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/promise.rb:531:in `block in realize'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
from /var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

Why is this error occurring? I am using the method as described [here](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/backup_protection_containers.rb#L40)

**Comment by vishrutshah** [comment]
@bilal-naeem-confiz I've talked to the service team. Although it is not clearly documented, seems like one of the filter `ContainerType` or `ProviderType` is expected from service side. Could you please give it a shot and let us know. 

Reference: https://docs.microsoft.com/en-us/rest/api/recoveryservices/protectioncontainers/list

Let me know so that we can improve the API via swagger or documentations.

**Comment by bilal-naeem-confiz** [comment]
@vishrutshah I have updated my script following the guide [here](https://docs.microsoft.com/en-us/rest/api/recoveryservices/protectioncontainers/list) and [here](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/backup_protection_containers.rb#L40)
```
require 'azure_mgmt_recovery_services_backup'

provider = MsRestAzure::ApplicationTokenProvider.new('########-####-####-####-############',
                                                     '########-####-####-####-############',
                                                     '############################################'
)
credentials = MsRest::TokenCredentials.new(provider)

recovery_services = Azure::ARM::RecoveryServicesBackup::RecoveryServicesBackupClient.new(credentials)
recovery_services.subscription_id = '########-####-####-####-############'

recovery_services.backup_protection_containers.list('TestVault', 'TestRG-RV', {providerType: 'AzureIaasVM', containerType: 'IaasVMContainer'})
```

I am still getting the same error as mentioned in my previous comment. I have tried passing `backupManagementType` as well but to no avail. What am I doing wrong at this point? Is there any other parameter which needs to be passed to the request?

**Comment by sarangan12** [comment]
@bilal-naeem-confiz If you are still facing this issue, Please reopen the issue. Since there is no movement on this issue for about 6 months, I am closing this issue
