### ISSUE TITLE
Service bus receive_queue_message got 400

### ISSUE THREAD

**Issue by maki5** [Azure/azure-sdk-for-ruby#655]
I'm working on simple queue functionality, send/receive messages using azure service bus queue. The send part is working ok, but when I try to get message from the queue I have this error:

```
Azure::Core::Http::HTTPError: 400 (400): 
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/http/http_request.rb:147:in `call'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-0.7.7/lib/azure/service_bus/service_bus_service.rb:41:in `call'

```
here is my code:

```
Azure.sb_namespace = "my_queue-test"
Azure.sb_access_key = "my_key"
queue_name = 'my_queue.all'
azure_service_bus_service = Azure.service_bus
message = azure_service_bus_service.receive_queue_message(queue_name,{ :peek_lock => false })


```

**Comment by sarangan12** [comment]
@maki5 

You need to use the proper signature to access the queue. From the code snippet provided, I am not able to determine if that has been done. So, I am providing a sample snippet that will work:

```
def get_message_from_queue
  Azure.configure do |config|
        config.sb_namespace    = "my_name_space"
        config.sb_sas_key_name = "my_queue_policy"
        config.sb_sas_key      = "my_sas_key"
  end
    
  signer = Azure::ServiceBus::Auth::SharedAccessSigner.new
  sb_host = "https://#{Azure.sb_namespace}.servicebus.windows.net"
  sbs = Azure::ServiceBus::ServiceBusService.new(sb_host, { signer: signer})
  message = sbs.receive_queue_message("my_queue_name",{ :peek_lock => false })
  return message.body unless message.nil?
  message
end

```

Let me know if you still have issues.

**Comment by maki5** [comment]
Sorry for delay, I just tried your code, but I still have 400 error with it

```
Azure.configure do |config|
  config.sb_namespace    = "my_namespace"
  config.sb_sas_key_name = "RootManageSharedAccessKey"
  config.sb_sas_key      = "my_key"
end

signer = Azure::ServiceBus::Auth::SharedAccessSigner.new
sb_host = "https://#{Azure.sb_namespace}.servicebus.windows.net"
sbs = Azure::ServiceBus::ServiceBusService.new(sb_host, { signer: signer})
message = sbs.receive_queue_message("my_queue.all",{ :peek_lock => false })

```

and here is the error:
```
Azure::Core::Http::HTTPError: 400 (400): 
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/http/http_request.rb:147:in `call'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-0.7.7/lib/azure/service_bus/service_bus_service.rb:41:in `call'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-0.7.7/lib/azure/service_bus/service_bus_service.rb:41:in `block in initialize'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/http/signer_filter.rb:28:in `call'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/http/signer_filter.rb:28:in `call'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/service.rb:36:in `call'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/filtered_service.rb:34:in `call'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-core-0.1.6/lib/azure/core/signed_service.rb:41:in `call'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-0.7.7/lib/azure/service_bus/service_bus_service.rb:662:in `_retrieve_message'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-0.7.7/lib/azure/service_bus/service_bus_service.rb:652:in `_read_delete_message'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-0.7.7/lib/azure/service_bus/service_bus_service.rb:544:in `read_delete_queue_message'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/azure-0.7.7/lib/azure/service_bus/service_bus_service.rb:579:in `receive_queue_message'
	from (irb):28
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/maki/Stuff/work/billing_api/bin/rails:9:in `<top (required)>'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/maki/.rvm/gems/ruby-2.3.1@wholesale/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/maki/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/maki/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
2.3.1 :029 > 

```

**Comment by sarangan12** [comment]
@maki5 

I think the problem might be in the line "message = sbs.receive_queue_message("my_queue.all",{ :peek_lock => false })" Can you confirm if your queue name is actually "my_queue.all".

**Comment by maki5** [comment]
yes, I'm able to push to it

**Comment by sarangan12** [comment]
Assigning it to @vishrutshah for now. I think the service team needs to be tagged.

**Comment by veronicagg** [comment]
@djrosanova, @jtaubensee, any comments on this?

**Comment by veronicagg** [comment]
@maki5 If you're still seeing this issue, could you share a fiddler trace or similar to help troubleshooting?

**Comment by sarangan12** [comment]
No activity on this issue. Closing this now. If you still have the issue please reopen it
