### ISSUE TITLE
MsRest::DeserializationError on fetching the VM list and subnet List

### ISSUE THREAD

**Issue by Nidhi10** [Azure/azure-sdk-for-ruby#778]
I am using 'azure_mgmt_compute' and 'azure_mgmt_network'.
I am trying to fetch list of subnets and VMs in my Resources group using two separate functions. Both  'get_list' and 'get_vm_list' fail with the same error - 
Methods - 
```
        def self.client(subscription_id)
          begin
            provider = MsRestAzure::ApplicationTokenProvider.new(
                ENV['AZURE_TENANT_ID'],
                ENV['AZURE_CLIENT_ID'],
                ENV['AZURE_SECRET_ID']
            )
            credentials = MsRest::TokenCredentials.new(provider)
            az_client = Azure::ARM::Resources::ResourceManagementClient.new(credentials)
            az_client.subscription_id = subscription_id
            az_client
          # rescue => e
            # logger.fatal "Exception while creating Azure client #{e.message}"
            # logger.fatal "Exception while creating Azure client #{e.backtrace}"
          end
        end

       def self.get_list(subscription_id, resource_group_name, virtual_network_name, subnet_name, expand = nil)
         network_obj = Azure::ARM::Network::Subnets.new(client(subscription_id))
         response = network_obj.get(resource_group_name, virtual_network_name, subnet_name, expand)
        end


        def self.get_vm_list(subscription_id, resource_group_name)
          network_obj = Azure::ARM::Compute::VirtualMachines.new(client(subscription_id))
          response = network_obj.list(resource_group_name) rescue nil
        end

```
Both return a MsRest::DeserializationError as follows -

```
MsRest::DeserializationError: {
  "exception_message": "uninitialized constant MsRestAzure::VirtualMachineListResult",
  "message": "Error occurred in deserializing the response",
  "stacktrace": [
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/ms_rest_azure-0.7.0/lib/ms_rest_azure/serialization.rb:37:in `const_get'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/ms_rest_azure-0.7.0/lib/ms_rest_azure/serialization.rb:37:in `rescue in get_model'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/ms_rest_azure-0.7.0/lib/ms_rest_azure/serialization.rb:33:in `get_model'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/ms_rest-0.6.4/lib/ms_rest/serialization.rb:160:in `deserialize_composite_type'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/ms_rest-0.6.4/lib/ms_rest/serialization.rb:68:in `deserialize'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/ms_rest-0.6.4/lib/ms_rest/serialization.rb:19:in `deserialize'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/azure_mgmt_compute-0.10.0/lib/generated/azure_mgmt_compute/virtual_machines.rb:515:in `block in list_async'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/promise.rb:501:in `block in on_fulfill'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/promise.rb:531:in `block in realize'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'",
    "/Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'"
  ],
  "result": {
    "response": {
      "body": "{....}",
      "headers": {
        "cache-control": "no-cache",
        "pragma": "no-cache",
        "content-type": "application/json; charset=utf-8",
        "expires": "-1",
        "vary": "Accept-Encoding",
        "strict-transport-security": "...",
        "x-ms-served-by": "....",
        "x-ms-request-id": "....",
        "server": "Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0",
        "x-ms-ratelimit-remaining-subscription-reads": "...",
        "x-ms-correlation-request-id": "....",
        "x-ms-routing-request-id": "",
        "date": "Mon, 15 May 2017 09:13:56 GMT",
        "connection": "close"
      },
      "status": 200
    },
    "request": {
      "base_uri": "https://management.azure.com",
      "path_template": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines",
      "method": "get",
      "path_params": {
        "resourceGroupName": "..",
        "subscriptionId": ".."
      },
      "skip_encoding_path_params": null,
      "query_params": {
        "api-version": "2016-04-30-preview"
      },
      "skip_encoding_query_params": null,
      "headers": {
        "Content-Type": "application/json;charset=utf-8",
        "accept-language": "en-US",
        "x-ms-client-request-id": ""
      },
      "body": null,
      "middlewares": [
        [
          "MsRest::RetryPolicyMiddleware",
          {
            "times": 3,
            "retry": 0.02
          }
        ],
        [
          "cookie_jar"
        ]
      ],
      "log": null
    }
  }
}
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/azure_mgmt_compute-0.10.0/lib/generated/azure_mgmt_compute/virtual_machines.rb:517:in `rescue in block in list_async'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/azure_mgmt_compute-0.10.0/lib/generated/azure_mgmt_compute/virtual_machines.rb:512:in `block in list_async'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/promise.rb:501:in `block in on_fulfill'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/promise.rb:531:in `block in realize'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	from /Users/nmittal/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

Could you please see what is wrong here.

**Comment by Nidhi10** [comment]
I was able to fix this myself. I had to create different clients to use compute and network services -

```
compute_client = Azure::ARM::Compute::ComputeManagementClient.new(set_creds)
network_client = Azure::ARM::Network::NetworkManagementClient.new(set_creds)
```
This solved the problem for me.
